
server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mblog.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com.mblog.mapper: debug/
imgSavePath: C:/Program Files/Code/JavaProject/blog-vue/public/mymd #生产/服务器环境：/home/tjx/blog/vue/dist/mymd/imgs/ 开发/本地环境：C:/Program Files/Code/JavaProject/blog-vue/public/mymd