sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQTEoZjHsSpf9jf4Lej
    access-key-secret: myejlmkvCcjOc2LFf8zU54rwxqNm07
    bucket-name: sky-tjx
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxf39b51044dcfe634
    secret: fb91742bab114eae5cece4bd6305b4e3