sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tB3ND8B1YdJJsEWtCNU
    access-key-secret: TCv658Td14rFMo17j5whyfylw8p9sY
    bucket-name: sky-tjx
